# Stage 1: install deps & bundle AdminJS
FROM node:22.21.1-alpine3.21 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run bundle:admin
RUN npm prune --omit=dev

# Stage 2: slim runtime image
FROM node:22.21.1-alpine3.21 AS runner
ENV NODE_ENV=production \
    PORT=4000
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 4000
CMD ["node", "server.js"]
